
redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  links:
    - redis
  volumes:
    - ./:/var/www/app
  ports:
    - 8080:8080
  environment:
    - NODE_ENV=development
    - PORT=8080
    - REDIS_URL=redis://cache
  command:
    sh -c 'npm i && node server.js'
